meta_product_name: "GLF"
meta_title: "GLF - Administrateur de biens"
meta_description: "Société spécialisée en gestion locative de locaux commerciaux et habitations en région parisienne depuis 35 ans."
meta_image: "republique.png" # should exist in `app/assets/images/`
